name: Read Secret and Save as Artifact

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'development'

jobs:
  read_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Save the secret to a file
        run: echo "${{ secrets.API_KEY }}" > secret.txt

      - name: Upload the secret as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: secret-file
          path: secret.txt
        
