name: Secrets

on:
  workflow_dispatch

jobs:
  top_secrets:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Here is your API_KEY
        run: echo "$API_KEY"
        
