name: Secrets

on:
  workflow_dispatch

jobs:
  top_secrets:
    runs-on: ubuntu-latest
    env:
      test: "test"
    steps:
      - name: Read a variable
        run: echo "API_KEY: ${{ vars.test }}"
