name: Secrets

on:
  workflow_dispatch

jobs:
  top_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action
        with: # Set the secret as an input
          super_secret: ${{ secrets.API_KEY }}
